version: "3.9"

services:
  db:
    image: mysql:lts
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=test_api
    ports:
      - 3306:3306
    volumes:
      - cl_db:/var/lib/mysql
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root1234

volumes:
  cl_db:
    driver: local
